// Copyright (C) 2009, 2010 by Florent Lamiraux, Thomas Moulard, JRL.
//
// This file is part of the hpp-corbaserver.
//
// This software is provided "as is" without warranty of any kind,
// either expressed or implied, including but not limited to the
// implied warranties of fitness for a particular purpose.
//
// See the COPYING file for more information.

#ifndef HPP_CORBASERVER_SERVER_IDL
# define HPP_CORBASERVER_SERVER_IDL

/// \brief main CORBA module.
module hpp
{
  /// Sequence of names
  typedef sequence <string> Names_t;
  /// Corba exception travelling through the Corba channel
  exception Error
  {
    string msg;
  };
  /// Robot configuration is defined by a sequence of dof value.
  typedef sequence<double> floatSeq;
  typedef sequence<floatSeq> floatSeqSeq;

  /// Element of SE(3) represented by a vector and a unit quaternion
  typedef double Transform [7];
};

#endif //! HPP_CORBASERVER_SERVER_IDL
