// Copyright (C) 2009, 2010 by Florent Lamiraux, Thomas Moulard, JRL.
//
// This file is part of the hpp-corbaserver.
//
// This software is provided "as is" without warranty of any kind,
// either expressed or implied, including but not limited to the
// implied warranties of fitness for a particular purpose.
//
// See the COPYING file for more information.

#ifndef HPP_SERVER_IDL
#define HPP_SERVER_IDL
#include <hpp/corbaserver/common.idl>

module hpp
{
  interface ServerIDL {
    /// Load a plugin that creates a CORBA interface.
    /// \param pluginName either an absolute filename or a filename relative
    ///                   to `<a_path_in_LD_LIBRARY_PATH>/hppPlugins`.
    /// \note The plugin will be available for any problem (even after resetting it).
    boolean loadServerPlugin (in string context_, in string pluginName) raises (Error);
  }; // interface ServerIDL
}; // module hpp
#endif
